# Generated by Django 3.2.4 on 2022-02-17 12:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='hjhj', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
